#!/bin/zsh

echo -e "\nChecking if node-shell is installed..."

if command -v kubectl-node_shell &>/dev/null; then
  echo "node-shell is already installed."
  exit 0
fi

echo -e "\nChecking if krew is installed...\n"

if command -v kubectl-krew &>/dev/null; then
  echo "krew is already installed. Installing node-shell..."
  kubectl krew install node-shell
  exit 0
fi

echo -e "\nInstalling krew...\n"
(
  set -x
  cd "$(mktemp -d)" &&
    OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
    ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
    KREW="krew-${OS}_${ARCH}" &&
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
    tar zxvf "${KREW}.tar.gz" &&
    ./"${KREW}" install krew
)
KREWPATH=${KREW_ROOT:-$HOME/.krew}/bin
echo 'export PATH=$PATH:'$KREWPATH >>~/.zprofile
export PATH=$PATH:$KREWPATH

echo -e "\nInstalling node-shell...\n"
kubectl krew install node-shell
