#!/usr/bin/env ruby

require 'json'
require 'date'

class Numeric
  def duration
    secs  = to_int
    mins  = secs / 60
    hours = mins / 60
    days  = hours / 24

    if days > 0
      "#{days} days and #{hours % 24} hours"
    elsif hours > 0
      "#{hours} hours and #{mins % 60} minutes"
    elsif mins > 0
      "#{mins} minutes and #{secs % 60} seconds"
    elsif secs >= 0
      "#{secs} seconds"
    end
  end
end

namespace = `kubectl config view --template='{{ range .contexts }}{{ if eq .name "'$(kubectl config current-context)'" }}{{ .context.namespace }}{{ end }}{{ end }}'`
pods_json = `kubectl --namespace #{namespace} get pods -o json`
pods_parsed = JSON.parse(pods_json)

puts 'The Magnificent Aging Plugin.'

data = {}
max_name_length = 0
max_age = 0
min_age = 0

pods_parsed['items'].each do |pod|
  name = pod['metadata']['name']
  creation = pod['metadata']['creationTimestamp']

  age = Time.now - DateTime.parse(creation).to_time
  data[name] = age

  max_name_length = name.length if name.length > max_name_length
  max_age = age if age > max_age
  min_age = age if age < min_age
end

data = data.sort_by { |_name, age| age }

if data.length > 0
  puts ''
  data.each do |name, age|
    output = ''
    output += name.rjust(max_name_length, ' ') + ': '
    bar_size = (age * 80 / max_age).ceil
    bar_size.times { output += '▒' }
    output += ' ' + age.duration
    puts output
    puts ''
  end
else
  puts 'No pods'
end
