name: Reusable E2E Test
on:
  workflow_call:
    inputs:
      target_tiab:
        required: true
        type: string
        description: 'Command with target tiab name'
      skip_e2e:
        required: true
        type: boolean
        description: 'whether we should skip the e2e test or not'

jobs:
  pr_commented:
    if: ${{ !inputs.skip_e2e }}
    name: Trigger E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Collect start time
        id: start_time
        run: |
          START_TIME="$(date -u +%s)"
          echo "VALUE=$START_TIME" >> $GITHUB_OUTPUT

      - name: Collect PR metadata
        uses: actions/github-script@v7
        id: pull_request_payload
        with:
          retries: 3
          script: |
            return github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ fromJson(steps.pull_request_payload.outputs.result).data.head.sha }}

      - name: comment start
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### \uD83E\uDD16 E2E Test has started.
            - By: @${{ github.triggering_actor }}
            - Branch: ${{ fromJson(steps.pull_request_payload.outputs.result).data.head.ref }}
            - Commit: ${{ fromJson(steps.pull_request_payload.outputs.result).data.head.sha }}
            - Test link: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            })

      - name: Step 1
        id: step1
        env:
          NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: ${{ inputs.target_tiab }}
          EMAIL: ${{ secrets.EMAIL_SEC }}
        run: |
          TEST=$(echo $COMMENT_BODY | awk '{print $2}')
          echo A comment on PR $NUMBER
          echo And the name is $TEST
          echo Email is $EMAIL
          echo current branch is $(git branch --show-current)
          echo and current commit it $(git rev-parse HEAD)
          RESULT=$(uname -a)
          echo "RESULT=$RESULT" >> $GITHUB_OUTPUT
          echo "TEST=$TEST" >> $GITHUB_OUTPUT

      - name: comment result
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '\u2705 E2E \u274c Test Result: ${{ steps.step1.outputs.RESULT }}. \n\n Comment was: ${{ steps.step1.outputs.TEST }}'
            })
