name: E2E Test
on: issue_comment
jobs:
  pr_commented:
    name: Trigger E2E Test
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/e2e-test') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/github-script@v7
        id: pull_request_payload
        with:
          result-encoding: string
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
      - run: echo "${{ steps.pull_request_payload.outputs.result }}"
      - name: comment start
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### \uD83E\uDD16 E2E Test has started.
            - By: @${{ github.triggering_actor }}
            - Branch: ${{ github.head_ref }}
            - Commit: ${{ github.event.pull_request.head.sha }}
            - Test link: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            })

      - name: Step 1
        id: step1
        env:
          NUMBER: ${{ github.event.issue.number }}
          TEST: ${{ github.event.comment.body }}
          EMAIL: ${{ secrets.EMAIL_SEC }}
        run: |
          echo A comment on PR $NUMBER
          echo And the name is $TEST
          echo Email is $EMAIL
          RESULT=$(uname -a)
          echo "RESULT=$RESULT" >> $GITHUB_OUTPUT

      - name: comment result
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '\u2705 E2E \u274c Test Result: ${{ steps.step1.outputs.RESULT }}'
            })
